version: '2.1'

services:
  wechat:
    image: wechat
    build: ../
    container_name: 'wechat'
    volumes:
      - dist:/usr/src/app/dist
    environment:
      NODE_ENV: production
  nginx_wechat:
    image: nginx
    ports:
      - 88:80
    container_name: 'nginx_wechat'
    restart: unless-stopped
    volumes:
      - dist:/usr/share/nginx/html:ro
volumes:
  dist:
