
version: '2.1'

services:
  wechat_build:
    build: ../
    container_name: 'wechat_build'
    volumes:
      - wechat_volume:/usr/src/app/dist

  wechat_web:
    image: nginx
    ports:
      - 163:80
    container_name: 'wechat_web'
    restart: unless-stopped
    # restart: always
    depends_on:
      - wechat_build
    volumes:
      - wechat_volume:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf

volumes:
  wechat_volume:
